drop extension if exists "pg_net";

create type "public"."app_role" as enum ('super_admin', 'leader', 'cashier', 'kitchen', 'pastor');


  create table "public"."cash_closures" (
    "id" uuid not null default gen_random_uuid(),
    "org_id" uuid,
    "closed_by" uuid,
    "closure_date" date not null,
    "opening_cash" numeric(12,2) default 0,
    "sales_total" numeric(12,2) default 0,
    "cash_counted" numeric(12,2) default 0,
    "expected_cash" numeric(12,2) default 0,
    "difference" numeric(12,2) default 0,
    "total_cash_sales" numeric(12,2) default 0,
    "total_card_sales" numeric(12,2) default 0,
    "total_transfer_sales" numeric(12,2) default 0,
    "orders_count" integer default 0,
    "notes" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."cash_closures" enable row level security;


  create table "public"."order_items" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint,
    "product_id" uuid,
    "name" text,
    "price" numeric,
    "quantity" integer,
    "subtotal" numeric,
    "created_at" timestamp with time zone default now(),
    "org_id" uuid
      );


alter table "public"."order_items" enable row level security;


  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "status" text default 'pending'::text,
    "total" numeric default 0,
    "customer_name" text,
    "group_id" integer,
    "updated_at" timestamp with time zone not null default now(),
    "paid_with" numeric not null default 0,
    "change" numeric not null default 0,
    "payment_method" text default 'cash'::text,
    "org_id" uuid,
    "created_by" uuid not null
      );


alter table "public"."orders" enable row level security;


  create table "public"."organizations" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "owner_id" uuid,
    "slug" text,
    "plan" text default 'free'::text,
    "status" text default 'trial'::text,
    "max_users" integer default 3,
    "stripe_customer_id" text,
    "stripe_subscription_id" text,
    "subscription_ends_at" timestamp with time zone
      );


alter table "public"."organizations" enable row level security;


  create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "org_id" uuid not null,
    "name" text not null,
    "price" numeric not null default 0,
    "category" text,
    "image" text,
    "active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."products" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "display_name" text,
    "org_id" uuid,
    "role" public.app_role not null default 'cashier'::public.app_role,
    "created_at" timestamp with time zone default now(),
    "auto_accept_orders" boolean default false,
    "owner_id" uuid,
    "onboarding_completed" boolean default false
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX cash_closures_pkey ON public.cash_closures USING btree (id);

CREATE INDEX idx_cash_closures_org_date ON public.cash_closures USING btree (org_id, closure_date DESC);

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);

CREATE INDEX idx_orders_created_by ON public.orders USING btree (created_by);

CREATE INDEX idx_orders_org_id ON public.orders USING btree (org_id);

CREATE INDEX idx_products_org_active ON public.products USING btree (org_id, active);

CREATE INDEX idx_products_org_name ON public.products USING btree (org_id, name);

CREATE INDEX idx_profiles_org_id ON public.profiles USING btree (org_id);

CREATE INDEX idx_profiles_owner_id ON public.profiles USING btree (owner_id);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."cash_closures" add constraint "cash_closures_pkey" PRIMARY KEY using index "cash_closures_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."cash_closures" add constraint "cash_closures_closed_by_fkey" FOREIGN KEY (closed_by) REFERENCES auth.users(id) not valid;

alter table "public"."cash_closures" validate constraint "cash_closures_closed_by_fkey";

alter table "public"."cash_closures" add constraint "cash_closures_org_id_fkey" FOREIGN KEY (org_id) REFERENCES public.organizations(id) not valid;

alter table "public"."cash_closures" validate constraint "cash_closures_org_id_fkey";

alter table "public"."order_items" add constraint "fk_order_items_product" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."order_items" validate constraint "fk_order_items_product";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

alter table "public"."orders" add constraint "fk_orders_org" FOREIGN KEY (org_id) REFERENCES public.organizations(id) not valid;

alter table "public"."orders" validate constraint "fk_orders_org";

alter table "public"."orders" add constraint "orders_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) not valid;

alter table "public"."orders" validate constraint "orders_created_by_fkey";

alter table "public"."organizations" add constraint "organizations_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES public.profiles(id) not valid;

alter table "public"."organizations" validate constraint "organizations_owner_id_fkey";

alter table "public"."organizations" add constraint "organizations_plan_check" CHECK ((plan = ANY (ARRAY['free'::text, 'starter'::text, 'pro'::text, 'enterprise'::text]))) not valid;

alter table "public"."organizations" validate constraint "organizations_plan_check";

alter table "public"."organizations" add constraint "organizations_status_check" CHECK ((status = ANY (ARRAY['trial'::text, 'active'::text, 'suspended'::text, 'cancelled'::text]))) not valid;

alter table "public"."organizations" validate constraint "organizations_status_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES public.profiles(id) not valid;

alter table "public"."profiles" validate constraint "profiles_owner_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.complete_onboarding()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public.profiles
  SET onboarding_completed = true
  WHERE id = auth.uid();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_new_user_rpc(new_email text, new_password text, new_role text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  creator_id uuid;
  creator_profile record;
  target_org_id uuid;
  new_user_id uuid;
  encrypted_pw text;
  v_instance_id uuid; -- <--- VARIABLE PARA GUARDAR EL ID REAL DEL PROYECTO
begin
  -- 1. Identificar al creador y SU INSTANCE_ID
  creator_id := auth.uid();
  if creator_id is null then
    raise exception 'No autenticado';
  end if;

  -- ðŸ•µï¸â€â™‚ï¸ OBTENER EL INSTANCE_ID REAL DEL PROYECTO
  select instance_id into v_instance_id from auth.users where id = creator_id;

  if v_instance_id is null then
     -- Fallback por si acaso (aunque no deberÃ­a pasar en cloud)
     v_instance_id := '00000000-0000-0000-0000-000000000000';
  end if;

  -- 2. Obtener datos del perfil del creador
  select * into creator_profile from public.profiles where id = creator_id;
  if creator_profile is null then
    raise exception 'Perfil del creador no encontrado';
  end if;

  -- 3. LÃ³gica "Smart Provisioning"
  if new_role = 'leader' then
    insert into public.organizations (name, slug)
    values ('Departamento - ' || split_part(new_email, '@', 1), gen_random_uuid()::text)
    returning id into target_org_id;
  else
    if creator_profile.org_id is null then
      raise exception 'El creador no pertenece a ninguna organizaciÃ³n para heredar.';
    end if;
    target_org_id := creator_profile.org_id;
  end if;

  -- 4. Generar ID y Password
  new_user_id := gen_random_uuid();
  encrypted_pw := crypt(new_password, gen_salt('bf'));

  -- 5. Insertar en auth.users (USANDO EL INSTANCE_ID REAL)
  insert into auth.users (
    instance_id, -- <--- AQUÃ USAMOS LA VARIABLE
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_user_meta_data,
    created_at,
    updated_at
  ) values (
    v_instance_id, -- <--- CORRECTO
    new_user_id,
    'authenticated',
    'authenticated',
    new_email,
    encrypted_pw,
    now(),
    jsonb_build_object('role', new_role),
    now(),
    now()
  );

  -- 6. Insertar en auth.identities
  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(),
    new_user_id,
    new_email,
    jsonb_build_object('sub', new_user_id, 'email', new_email, 'email_verified', true, 'phone_verified', false),
    'email',
    now(), now(), now()
  );

  -- 7. Insertar en public.profiles
  begin
    insert into public.profiles (id, email, role, org_id, display_name)
    values (
      new_user_id,
      new_email,
      new_role::public.app_role,
      target_org_id,
      split_part(new_email, '@', 1)
    );
  exception when unique_violation then
    update public.profiles
    set org_id = target_org_id,
        role = new_role::public.app_role
    where id = new_user_id;
  end;

  return json_build_object(
    'message', 'Usuario creado exitosamente (v3.0 - Instance ID Fix)',
    'id', new_user_id,
    'org_id', target_org_id
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_user_cascade(target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  caller_id uuid;
  caller_role text;
  target_profile record;
  sub_profile record;
BEGIN
  caller_id := auth.uid();
  IF caller_id IS NULL THEN RAISE EXCEPTION 'No autenticado'; END IF;

  SELECT role INTO caller_role FROM public.profiles WHERE id = caller_id;
  SELECT * INTO target_profile FROM public.profiles WHERE id = target_user_id;

  IF target_profile IS NULL THEN RAISE EXCEPTION 'Usuario no encontrado'; END IF;

  -- Solo el owner directo o super_admin pueden eliminar
  IF caller_role != 'super_admin' AND target_profile.owner_id != caller_id THEN
    RAISE EXCEPTION 'No tienes permisos para eliminar este usuario';
  END IF;

  -- Proteger cuenta maestra
  IF target_profile.email = 'admin@genesis.com' THEN
    RAISE EXCEPTION 'No se puede eliminar la cuenta maestra';
  END IF;

  -- Recursividad: eliminar subordinados primero
  FOR sub_profile IN SELECT * FROM public.profiles WHERE owner_id = target_user_id
  LOOP
    PERFORM delete_user_cascade(sub_profile.id);
  END LOOP;

  -- Solo borrar datos de la org si es lÃ­der o pastor (NO si es cajero/cocina)
  -- Borrar un cajero no debe eliminar el inventario del lÃ­der
  IF target_profile.org_id IS NOT NULL AND target_profile.role NOT IN ('cashier', 'kitchen') THEN
    DELETE FROM public.order_items WHERE order_id IN (
      SELECT id FROM public.orders WHERE org_id = target_profile.org_id
    );
    DELETE FROM public.orders WHERE org_id = target_profile.org_id;
    DELETE FROM public.products WHERE org_id = target_profile.org_id;
  END IF;

  -- Eliminar perfil
  DELETE FROM public.profiles WHERE id = target_user_id;

  -- Limpiar org fantasma
  IF target_profile.org_id IS NOT NULL THEN
    DELETE FROM public.organizations WHERE id = target_profile.org_id
      AND NOT EXISTS (SELECT 1 FROM public.profiles WHERE org_id = target_profile.org_id);
  END IF;

  -- Liberar email para reuso
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_user_from_auth()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  delete from auth.users where id = old.id;
  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_org()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT org_id FROM public.profiles WHERE id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_org_id()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT org_id FROM public.profiles WHERE id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  -- Convertimos el app_role a texto al salir para evitar conflictos de tipos en las comparaciones
  SELECT role::text FROM public.profiles WHERE id = auth.uid();
$function$
;

create or replace view "public"."orders_full_view" as  SELECT o.id,
    o.created_at,
    o.status,
    o.total,
    o.customer_name,
    o.payment_method,
    o.org_id,
    COALESCE(jsonb_agg(jsonb_build_object('id', oi.id, 'name', oi.name, 'quantity', oi.quantity, 'price', oi.price, 'subtotal', oi.subtotal)) FILTER (WHERE (oi.id IS NOT NULL)), '[]'::jsonb) AS items
   FROM (public.orders o
     LEFT JOIN public.order_items oi ON ((o.id = oi.order_id)))
  GROUP BY o.id;


CREATE OR REPLACE FUNCTION public.provision_user_profile(target_user_id uuid, user_email text, user_role text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  creator_id uuid;
  creator_profile record;
  target_org_id uuid;
BEGIN
  creator_id := auth.uid();
  IF creator_id IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  SELECT * INTO creator_profile FROM public.profiles WHERE id = creator_id;
  IF creator_profile IS NULL THEN
    RAISE EXCEPTION 'Perfil del creador no encontrado';
  END IF;

  -- Pastor y Leader = OrganizaciÃ³n PROPIA (aislamiento total)
  IF user_role IN ('leader', 'pastor') THEN
    INSERT INTO public.organizations (name, slug)
    VALUES (
      CASE user_role
        WHEN 'pastor' THEN 'Iglesia - ' || split_part(user_email, '@', 1)
        WHEN 'leader' THEN 'Departamento - ' || split_part(user_email, '@', 1)
      END,
      gen_random_uuid()::text
    )
    RETURNING id INTO target_org_id;
  ELSE
    -- Staff (cashier, kitchen) = Hereda la org del creador
    IF creator_profile.org_id IS NULL THEN
      RAISE EXCEPTION 'El creador no pertenece a ninguna organizaciÃ³n para heredar.';
    END IF;
    target_org_id := creator_profile.org_id;
  END IF;

  INSERT INTO public.profiles (id, email, role, org_id, display_name, onboarding_completed)
  VALUES (
    target_user_id,
    user_email,
    user_role::public.app_role,
    target_org_id,
    split_part(user_email, '@', 1),
    true
  )
  ON CONFLICT (id) DO UPDATE
  SET role = excluded.role,
      org_id = excluded.org_id,
      onboarding_completed = true;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.provision_user_profile(target_user_id uuid, user_email text, user_role text, user_display_name text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  creator_id uuid;
  creator_profile record;
  target_org_id uuid;
BEGIN
  creator_id := auth.uid();
  IF creator_id IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  SELECT * INTO creator_profile FROM public.profiles WHERE id = creator_id;
  IF creator_profile IS NULL THEN
    RAISE EXCEPTION 'Perfil del creador no encontrado';
  END IF;

  -- Solo PASTOR obtiene org nueva (su iglesia)
  -- LÃ­der y Staff heredan la org del creador
  IF user_role = 'pastor' THEN
    INSERT INTO public.organizations (name, slug)
    VALUES ('Iglesia - ' || COALESCE(user_display_name, split_part(user_email, '@', 1)), gen_random_uuid()::text)
    RETURNING id INTO target_org_id;
  ELSE
    IF creator_profile.org_id IS NULL THEN
      RAISE EXCEPTION 'El creador no pertenece a ninguna organizaciÃ³n.';
    END IF;
    target_org_id := creator_profile.org_id;
  END IF;

  -- Insertar perfil con owner_id y display_name
  INSERT INTO public.profiles (id, email, role, org_id, owner_id, display_name, onboarding_completed)
  VALUES (
    target_user_id,
    user_email,
    user_role::public.app_role,
    target_org_id,
    creator_id,  -- owner_id = quien lo creÃ³
    COALESCE(user_display_name, split_part(user_email, '@', 1)),
    true
  )
  ON CONFLICT (id) DO UPDATE
  SET role = excluded.role,
      org_id = excluded.org_id,
      owner_id = excluded.owner_id,
      display_name = excluded.display_name,
      onboarding_completed = true;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_created_by()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NEW.created_by IS NULL THEN
    NEW.created_by := auth.uid();
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.setup_new_tenant(p_church_name text, p_church_slug text, p_full_name text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id UUID;
  v_org_id UUID;
BEGIN
  -- 1. Obtener ID del usuario autenticado
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  -- 2. Validar que el slug no exista
  IF EXISTS (SELECT 1 FROM public.organizations WHERE slug = p_church_slug) THEN
    RAISE EXCEPTION 'El nombre de iglesia "%" ya estÃ¡ en uso', p_church_name;
  END IF;

  -- 3. Crear organizaciÃ³n (ACID transaction)
  INSERT INTO public.organizations (name, slug, plan, status, max_users, owner_id)
  VALUES (p_church_name, p_church_slug, 'free', 'trial', 3, v_user_id)
  RETURNING id INTO v_org_id;

  -- 4. Actualizar profile (que el trigger handle_new_user ya creÃ³)
  UPDATE public.profiles
  SET
    org_id = v_org_id,
    display_name = p_full_name,
    onboarding_completed = FALSE
  WHERE id = v_user_id;

  -- 5. Retornar Ã©xito
  RETURN json_build_object(
    'success', true,
    'org_id', v_org_id,
    'message', 'Tenant creado exitosamente'
  );

EXCEPTION WHEN OTHERS THEN
  RAISE EXCEPTION 'Error al crear tenant: %', SQLERRM;
END;
$function$
;

grant delete on table "public"."cash_closures" to "anon";

grant insert on table "public"."cash_closures" to "anon";

grant references on table "public"."cash_closures" to "anon";

grant select on table "public"."cash_closures" to "anon";

grant trigger on table "public"."cash_closures" to "anon";

grant truncate on table "public"."cash_closures" to "anon";

grant update on table "public"."cash_closures" to "anon";

grant delete on table "public"."cash_closures" to "authenticated";

grant insert on table "public"."cash_closures" to "authenticated";

grant references on table "public"."cash_closures" to "authenticated";

grant select on table "public"."cash_closures" to "authenticated";

grant trigger on table "public"."cash_closures" to "authenticated";

grant truncate on table "public"."cash_closures" to "authenticated";

grant update on table "public"."cash_closures" to "authenticated";

grant delete on table "public"."cash_closures" to "service_role";

grant insert on table "public"."cash_closures" to "service_role";

grant references on table "public"."cash_closures" to "service_role";

grant select on table "public"."cash_closures" to "service_role";

grant trigger on table "public"."cash_closures" to "service_role";

grant truncate on table "public"."cash_closures" to "service_role";

grant update on table "public"."cash_closures" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."organizations" to "anon";

grant insert on table "public"."organizations" to "anon";

grant references on table "public"."organizations" to "anon";

grant select on table "public"."organizations" to "anon";

grant trigger on table "public"."organizations" to "anon";

grant truncate on table "public"."organizations" to "anon";

grant update on table "public"."organizations" to "anon";

grant delete on table "public"."organizations" to "authenticated";

grant insert on table "public"."organizations" to "authenticated";

grant references on table "public"."organizations" to "authenticated";

grant select on table "public"."organizations" to "authenticated";

grant trigger on table "public"."organizations" to "authenticated";

grant truncate on table "public"."organizations" to "authenticated";

grant update on table "public"."organizations" to "authenticated";

grant delete on table "public"."organizations" to "service_role";

grant insert on table "public"."organizations" to "service_role";

grant references on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "service_role";

grant trigger on table "public"."organizations" to "service_role";

grant truncate on table "public"."organizations" to "service_role";

grant update on table "public"."organizations" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Members view own org closures"
  on "public"."cash_closures"
  as permissive
  for select
  to public
using ((org_id = public.get_my_org()));



  create policy "Staff can insert closures"
  on "public"."cash_closures"
  as permissive
  for insert
  to public
with check ((org_id = public.get_my_org()));



  create policy "SuperAdmin manages all closures"
  on "public"."cash_closures"
  as permissive
  for all
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "order_items_delete_by_org"
  on "public"."order_items"
  as permissive
  for delete
  to public
using ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.org_id = public.get_my_org())))));



  create policy "order_items_insert_by_org"
  on "public"."order_items"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.org_id = public.get_my_org())))));



  create policy "order_items_select_by_org"
  on "public"."order_items"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.org_id = public.get_my_org())))));



  create policy "order_items_superadmin"
  on "public"."order_items"
  as permissive
  for all
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "order_items_update_by_org"
  on "public"."order_items"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.org_id = public.get_my_org())))));



  create policy "Kitchen can update order status"
  on "public"."orders"
  as permissive
  for update
  to public
using (((public.get_my_role() = 'kitchen'::text) AND (org_id = public.get_my_org())))
with check (true);



  create policy "Leaders can manage org orders"
  on "public"."orders"
  as permissive
  for all
  to public
using (((public.get_my_role() = 'leader'::text) AND (org_id = public.get_my_org())));



  create policy "Pastor can manage org orders"
  on "public"."orders"
  as permissive
  for all
  to public
using (((public.get_my_role() = 'pastor'::text) AND (org_id = public.get_my_org())));



  create policy "Staff can create orders"
  on "public"."orders"
  as permissive
  for insert
  to public
with check (((public.get_my_role() = ANY (ARRAY['cashier'::text, 'kitchen'::text])) AND (org_id = public.get_my_org())));



  create policy "Staff can view org orders"
  on "public"."orders"
  as permissive
  for select
  to public
using (((public.get_my_role() = ANY (ARRAY['cashier'::text, 'kitchen'::text])) AND (org_id = public.get_my_org())));



  create policy "Super Admin can manage all orders"
  on "public"."orders"
  as permissive
  for all
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "Pastor can update own org"
  on "public"."organizations"
  as permissive
  for update
  to public
using (((public.get_my_role() = 'pastor'::text) AND (id = public.get_my_org())))
with check (((public.get_my_role() = 'pastor'::text) AND (id = public.get_my_org())));



  create policy "organizations_select_own"
  on "public"."organizations"
  as permissive
  for select
  to public
using ((id = public.get_my_org()));



  create policy "organizations_superadmin"
  on "public"."organizations"
  as permissive
  for all
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "Staff can manage org products"
  on "public"."products"
  as permissive
  for all
  to public
using (((public.get_my_role() = ANY (ARRAY['pastor'::text, 'leader'::text, 'cashier'::text, 'kitchen'::text])) AND (org_id = public.get_my_org())));



  create policy "Super Admin manages all products"
  on "public"."products"
  as permissive
  for all
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "Hierarchy read access"
  on "public"."profiles"
  as permissive
  for select
  to public
using (((id = auth.uid()) OR (public.get_my_role() = 'super_admin'::text) OR (owner_id = auth.uid())));



  create policy "Jerarquia de Creacion"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check (
CASE public.get_my_role()
    WHEN 'super_admin'::text THEN true
    WHEN 'pastor'::text THEN (role = ANY (ARRAY['leader'::public.app_role, 'cashier'::public.app_role, 'kitchen'::public.app_role]))
    WHEN 'leader'::text THEN (role = ANY (ARRAY['cashier'::public.app_role, 'kitchen'::public.app_role]))
    ELSE false
END);



  create policy "Leaders can update org staff"
  on "public"."profiles"
  as permissive
  for update
  to public
using (((public.get_my_role() = 'leader'::text) AND (org_id = public.get_my_org()) AND ((role)::text = ANY (ARRAY['cashier'::text, 'kitchen'::text]))))
with check (((role)::text = ANY (ARRAY['cashier'::text, 'kitchen'::text])));



  create policy "Leaders can view org profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using (((public.get_my_role() = 'leader'::text) AND (org_id = public.get_my_org())));



  create policy "Managers can delete their staff"
  on "public"."profiles"
  as permissive
  for delete
  to public
using (((public.get_my_role() = 'super_admin'::text) OR (owner_id = auth.uid())));



  create policy "Managers can update their staff"
  on "public"."profiles"
  as permissive
  for update
  to public
using (((public.get_my_role() = 'super_admin'::text) OR (owner_id = auth.uid())))
with check (((public.get_my_role() = 'super_admin'::text) OR (owner_id = auth.uid())));



  create policy "Pastor can view all profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((public.get_my_role() = 'pastor'::text));



  create policy "Super Admin can delete profiles"
  on "public"."profiles"
  as permissive
  for delete
  to public
using (((public.get_my_role() = 'super_admin'::text) AND (email <> 'admin@genesis.com'::text)));



  create policy "Super Admin can update all profiles"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((public.get_my_role() = 'super_admin'::text))
with check ((NOT ((email = 'admin@genesis.com'::text) AND ((role)::text <> 'super_admin'::text))));



  create policy "Super Admin can view all profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((public.get_my_role() = 'super_admin'::text));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check (((auth.uid() = id) AND (role = ( SELECT profiles_1.role
   FROM public.profiles profiles_1
  WHERE (profiles_1.id = auth.uid())))));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));


CREATE TRIGGER trigger_set_created_by BEFORE INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

CREATE TRIGGER on_profile_delete AFTER DELETE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.delete_user_from_auth();


  create policy "Anyone can view org logos"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'org-logos'::text));



  create policy "Users can update own org logo"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'org-logos'::text) AND ((storage.foldername(name))[1] = ( SELECT (profiles.org_id)::text AS org_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))));



  create policy "Users can upload own org logo"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'org-logos'::text) AND ((storage.foldername(name))[1] = ( SELECT (profiles.org_id)::text AS org_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))));
